### ISSUE TITLE
Consider adding a LICENSE

### ISSUE THREAD

**Issue by xdevs23** [Evolution-XYZ/vendor_evolution-priv_keys-template#1]
I really like that this repository has a script for setting up the keys. It would be nice if this repository had a LICENSE file so that other ROMs using this repository are on the safe side and to make sure that it's libre and open source. The current state, although public, is "All Rights Reserved" and without any right and freedom to modify and distribute.

**Comment by AnierinBliss** [comment]
https://github.com/Evolution-XYZ/vendor_evolution-priv_keys-template/commit/459fd3baad6be84746c93941caf8160dec20a528
